name: Exadel-Task-Four

on:
    push:
        branches:
                - master

env:
    DOCKER_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
    DOCKER_PASS: ${{ secrets.DOCKER_HUB_PASSWORD }}
    PROJECT: ${{ secrets.PROJECT }}

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Docker login
          run: docker login --username $DOCKER_USER --password $DOCKER_PASS
        - name: Build the Docker image
          run: docker build -t $DOCKE_USER/$PROJECT:latest ./task_4/.
        - name: Push Docker image to dockerhub
          run: docker push $DOCKE_USER/$PROJECT:latest
        
