name: Exadel-Task-Four

on:
    push:
        branches:
                - master

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Docker login
          run: docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password ${{ DOCKER_HUB_PASSWORD }}
        - name: Build the Docker image
          run: docker build -t '${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.PROJECT }}:latest ./task_4/'
        - name: Push Docker image to dockerhub
          run: docker push '${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.PROJECT }}:latest'
        
